// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vscode from "vscode";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Node from "vscode-languageclient/node";

let client = {
  contents: undefined
};

function startLanguageClient(_context) {
  let config = Vscode.workspace.getConfiguration("wokelang");
  let path = config.get("serverPath");
  let serverPath = path !== undefined ? path : "woke-lsp";
  let serverOptions_run = {
    command: serverPath,
    transport: 0
  };
  let serverOptions_debug = {
    command: serverPath,
    transport: 0,
    options: {
      env: Js_dict.fromArray([[
          "RUST_BACKTRACE",
          "1"
        ]])
    }
  };
  let serverOptions = {
    run: serverOptions_run,
    debug: serverOptions_debug
  };
  let clientOptions_documentSelector = [{
      scheme: "file",
      language: "wokelang"
    }];
  let clientOptions_synchronize = {
    fileEvents: Vscode.workspace.createFileSystemWatcher("**/*.woke")
  };
  let clientOptions = {
    documentSelector: clientOptions_documentSelector,
    synchronize: clientOptions_synchronize
  };
  let languageClient = new Node.LanguageClient("wokelang", "WokeLang Language Server", serverOptions, clientOptions);
  client.contents = Primitive_option.some(languageClient);
  languageClient.start();
}

function restartServer(context) {
  let c = client.contents;
  if (c !== undefined) {
    Primitive_option.valFromOption(c).stop();
    return startLanguageClient(context);
  } else {
    return startLanguageClient(context);
  }
}

function showInfo() {
  Vscode.window.showInformationMessage("WokeLang LSP extension v0.1.0 - Consent-aware programming language");
}

function checkConsent() {
  Vscode.window.showInformationMessage("Consent safety check: Analyzing capability usage patterns...");
}

function formatDocument() {
  Vscode.window.showInformationMessage("Formatting with WokeLang formatter...");
}

function activate(context) {
  startLanguageClient(context);
  let restartCmd = Vscode.commands.registerCommand("wokelang.restartServer", () => new Promise((resolve, param) => {
    restartServer(context);
    resolve();
  }));
  let infoCmd = Vscode.commands.registerCommand("wokelang.showInfo", () => new Promise((resolve, param) => {
    Vscode.window.showInformationMessage("WokeLang LSP extension v0.1.0 - Consent-aware programming language");
    resolve();
  }));
  let consentCmd = Vscode.commands.registerCommand("wokelang.checkConsent", () => new Promise((resolve, param) => {
    Vscode.window.showInformationMessage("Consent safety check: Analyzing capability usage patterns...");
    resolve();
  }));
  let formatCmd = Vscode.commands.registerCommand("wokelang.formatDocument", () => new Promise((resolve, param) => {
    Vscode.window.showInformationMessage("Formatting with WokeLang formatter...");
    resolve();
  }));
  context.subscriptions.push(restartCmd);
  context.subscriptions.push(infoCmd);
  context.subscriptions.push(consentCmd);
  context.subscriptions.push(formatCmd);
}

function deactivate() {
  let c = client.contents;
  if (c !== undefined) {
    return Primitive_option.valFromOption(c).stop();
  }
}

export {
  client,
  startLanguageClient,
  restartServer,
  showInfo,
  checkConsent,
  formatDocument,
  activate,
  deactivate,
}
/* vscode Not a pure module */
