// Generated by ReScript, PLEASE EDIT WITH CARE


let Workspace = {};

let Window = {};

let Commands = {};

let LanguageClient = {};

export {
  Workspace,
  Window,
  Commands,
  LanguageClient,
}
/* No side effect */
