// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE


let Workspace = {};

let Window = {};

let Commands = {};

let LanguageClient = {};

export {
  Workspace,
  Window,
  Commands,
  LanguageClient,
}
/* No side effect */
